apiVersion: eventing.knative.dev/v1
kind: Trigger
metadata:
  name: invoices-subscription
spec:
  broker: orders-dispatcher
  filter:
    attributes:
      fraudscore: high
  subscriber:
    ref:
      apiVersion: serving.knative.dev/v1
      kind: Service
      name: order-invoicer
